// Every enemy type as data. A type says how it behaves, not how it looks - the
// look lives in render3d/models.js under the same key.
//
// hp is in player shots at sector 1; later sectors multiply it (config.tierFor).
// speed is in world units per second. The player moves at 7.4, and nothing
// outside a telegraphed dash is as fast.

export const ENEMIES = {
  sentry: {
    name: 'Sentry',
    blurb: 'Fixed gun emplacement. Tracks you, never moves.',
    hp: 5,
    r: 0.42,
    behavior: 'static',
    pattern: 'aimed',
    solid: true,
    turn: 3.2,
  },
  hunter: {
    name: 'Hunter',
    blurb: 'Keeps its distance and circles you while it shoots.',
    hp: 4,
    r: 0.36,
    behavior: 'hunter',
    pattern: 'aimed',
    speed: 3.4,
    standoff: 5.2,
    contact: true,
    turn: 7,
  },
  ram: {
    name: 'Ram',
    blurb: 'Locks on, flashes, then dashes in a straight line. Sidestep.',
    hp: 7,
    r: 0.44,
    behavior: 'charger',
    pattern: null,
    speed: 2.0,
    dash: 12.5,
    contact: true,
    turn: 4,
  },
  orbiter: {
    name: 'Orbiter',
    blurb: 'Circles the core and fires twin shots.',
    hp: 4,
    r: 0.34,
    behavior: 'orbit',
    pattern: 'twin',
    speed: 2.8,
    orbit: 3.4,
    turn: 8,
  },
  spinner: {
    name: 'Spinner',
    blurb: 'A turning blade that sprays spirals.',
    hp: 10,
    r: 0.56,
    behavior: 'drift',
    pattern: 'spiral',
    speed: 0.8,
    spin: 1.5,
    solid: true,
  },
  splitter: {
    name: 'Splitter',
    blurb: 'Breaks into three shards when destroyed.',
    hp: 7,
    r: 0.5,
    behavior: 'chase',
    pattern: 'spread',
    speed: 1.9,
    contact: true,
    turn: 5,
    split: { type: 'shard', count: 3 },
  },
  shard: {
    name: 'Shard',
    blurb: 'Fast fragment of a Splitter. One hit.',
    hp: 1,
    r: 0.24,
    behavior: 'chase',
    pattern: null,
    speed: 5.0,
    contact: true,
    turn: 9,
  },
  weaver: {
    name: 'Weaver',
    blurb: 'Wanders the arena laying mines. Shoot the mines before they burst.',
    hp: 7,
    r: 0.44,
    behavior: 'wander',
    pattern: null,
    speed: 2.6,
    ability: 'mines',
    abilityEvery: 2.3,
    turn: 5,
  },
  lancer: {
    name: 'Lancer',
    blurb: 'Charges a beam along its aim. The red line shows where.',
    hp: 6,
    r: 0.4,
    behavior: 'static',
    pattern: 'beam',
    solid: true,
    turn: 1.7,
  },
  warden: {
    name: 'Warden',
    blurb: 'Shields every enemy near it. Kill it first.',
    hp: 8,
    r: 0.46,
    behavior: 'wander',
    pattern: null,
    speed: 1.6,
    ability: 'shield',
    range: 6.5,
    turn: 3,
  },
  mortar: {
    name: 'Mortar',
    blurb: 'Lobs shells at where you stand. Leave the circle.',
    hp: 7,
    r: 0.48,
    behavior: 'static',
    pattern: 'mortar',
    solid: true,
    turn: 2.2,
  },
  phantom: {
    name: 'Phantom',
    blurb: 'Blinks across the arena and bursts on arrival.',
    hp: 5,
    r: 0.36,
    behavior: 'blink',
    pattern: 'ringSmall',
    turn: 6,
  },
  wasp: {
    name: 'Wasp',
    blurb: 'Swarms in weaving packs. Fragile, fast, bites on contact.',
    hp: 1,
    r: 0.22,
    behavior: 'swarm',
    pattern: null,
    speed: 5.2,
    contact: true,
    turn: 6,
  },
  bulwark: {
    name: 'Bulwark',
    blurb: 'Armoured at the front, turns slowly. Hit it from behind.',
    hp: 10,
    r: 0.56,
    behavior: 'tank',
    pattern: 'spread',
    // Slow to turn on purpose: the gap it leaves is the whole fight.
    speed: 1.15,
    armored: true,
    contact: true,
    turn: 0.95,
  },
}

// The order the legend in the menu lists them in, which is also roughly the
// order they first show up.
export const ENEMY_ORDER = [
  'sentry',
  'hunter',
  'ram',
  'lancer',
  'wasp',
  'splitter',
  'bulwark',
  'mortar',
  'orbiter',
  'weaver',
  'spinner',
  'phantom',
  'warden',
  'shard',
]
